import Header from "../layout/header/header";
import { vazir } from "../fonts/font";
import "./globals.css"


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function dass() {
  return <div></div>
}

dass.g
export default function getLayout({ children }) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body className={vazir.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
